version: '3.8'

services:
  app:
    container_name: wender-tech-portfolio
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    # As variáveis de ambiente serão injetadas pelo Portainer
    environment:
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - DATABASE_URL
      - NEXT_PUBLIC_APP_URL
      - NEXT_PUBLIC_APP_NAME
      - NEXT_PUBLIC_APP_DESCRIPTION
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - NODE_ENV
      - NEXT_PUBLIC_PRODUCTION
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/api/check-env',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
